# DESCRIPTION: intelligent server mock
node:
  image: 'dekka/node:latest'
  environment:
    DEKKA_APP_NAME: imock-server
  volumes:
    - /opt/dekka/imock/server:/opt/node
  ports:
    - 8080:3000/tcp
    - 8090:5858/tcp
  links:
    - redis

gui:
  image: 'dekka/node:latest'
  environment:
    DEKKA_APP_NAME: imock-gui
  volumes:
    - /opt/dekka/imock/gui:/opt/node
  ports:
    - 8081:3000/tcp
    - 8091:5858/tcp
  links:
    - redis

redis-commander:
  image: 'dekka/redis-commander:latest'
  command: --redis-host redis
  ports:
    - 8082:8081/tcp  
  links:
    - redis

redis:
  image: 'dekka/redis:latest'
